deploy:
  name: Deploy to Hostinger
  runs-on: ubuntu-latest
  needs: test
  if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start SSH agent and add key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

    - name: Deploy via rsync
      run: |
        rsync -avz -e "ssh -p 65002" --delete ./ \
          ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:/home/${{ secrets.HOSTINGER_USER }}/public_html
